import random
from django.core.management.base import BaseCommand
from django.utils.text import slugify
from domain.models import Category, Product


CATEGORIES = [
    {'name': 'Điện thoại', 'slug': 'dien-thoai', 'description': 'Smartphone và phụ kiện'},
    {'name': 'Laptop', 'slug': 'laptop', 'description': 'Laptop và máy tính xách tay'},
    {'name': 'Thời trang Nam', 'slug': 'thoi-trang-nam', 'description': 'Quần áo, giày dép nam'},
    {'name': 'Thời trang Nữ', 'slug': 'thoi-trang-nu', 'description': 'Quần áo, giày dép nữ'},
    {'name': 'Đồ gia dụng', 'slug': 'do-gia-dung', 'description': 'Thiết bị gia dụng thông minh'},
    {'name': 'Sách', 'slug': 'sach', 'description': 'Sách và tài liệu'},
    {'name': 'Thể thao', 'slug': 'the-thao', 'description': 'Dụng cụ và trang phục thể thao'},
    {'name': 'Mỹ phẩm', 'slug': 'my-pham', 'description': 'Mỹ phẩm và chăm sóc cá nhân'},
    {'name': 'Đồng hồ', 'slug': 'dong-ho', 'description': 'Đồng hồ thông minh và đồng hồ thời trang'},
    {'name': 'Thiết bị âm thanh', 'slug': 'am-thanh', 'description': 'Tai nghe, loa bluetooth và thiết bị âm thanh'},
]

PRODUCTS = {
    'dien-thoai': [
        {'name': 'iPhone 15 Pro Max', 'brand': 'Apple', 'price': 34990000, 'compare_price': 38990000,
         'specs': {'ram': '8GB', 'storage': '256GB', 'screen': '6.7 inch', 'chip': 'A17 Pro', 'camera': '48MP'},
         'image': 'https://picsum.photos/seed/iphone15promax/400/400'},
        {'name': 'Samsung Galaxy S24 Ultra', 'brand': 'Samsung', 'price': 31990000, 'compare_price': 35990000,
         'specs': {'ram': '12GB', 'storage': '256GB', 'screen': '6.8 inch', 'chip': 'Snapdragon 8 Gen 3', 'camera': '200MP'},
         'image': 'https://picsum.photos/seed/s24ultra/400/400'},
        {'name': 'Xiaomi 14', 'brand': 'Xiaomi', 'price': 12990000, 'compare_price': 14990000,
         'specs': {'ram': '12GB', 'storage': '256GB', 'screen': '6.36 inch', 'chip': 'Snapdragon 8 Gen 3'},
         'image': 'https://picsum.photos/seed/xiaomi14/400/400'},
        {'name': 'OPPO Find X7 Ultra', 'brand': 'OPPO', 'price': 23990000, 'compare_price': None,
         'specs': {'ram': '16GB', 'storage': '512GB', 'screen': '6.82 inch', 'camera': 'Hasselblad'},
         'image': 'https://picsum.photos/seed/oppofindx7/400/400'},
        {'name': 'Google Pixel 8 Pro', 'brand': 'Google', 'price': 18990000, 'compare_price': 21990000,
         'specs': {'ram': '12GB', 'storage': '128GB', 'screen': '6.7 inch', 'chip': 'Tensor G3'},
         'image': 'https://picsum.photos/seed/pixel8pro/400/400'},
        {'name': 'iPhone 15', 'brand': 'Apple', 'price': 22990000, 'compare_price': 24990000,
         'specs': {'ram': '6GB', 'storage': '128GB', 'screen': '6.1 inch', 'chip': 'A16 Bionic'},
         'image': 'https://picsum.photos/seed/iphone15base/400/400'},
        {'name': 'Samsung Galaxy A55', 'brand': 'Samsung', 'price': 9990000, 'compare_price': 10990000,
         'specs': {'ram': '8GB', 'storage': '128GB', 'screen': '6.6 inch', 'chip': 'Exynos 1480'},
         'image': 'https://picsum.photos/seed/galaxya55/400/400'},
        {'name': 'Xiaomi Redmi Note 13 Pro', 'brand': 'Xiaomi', 'price': 7990000, 'compare_price': 8990000,
         'specs': {'ram': '8GB', 'storage': '256GB', 'screen': '6.67 inch', 'camera': '200MP'},
         'image': 'https://picsum.photos/seed/redminote13/400/400'},
        {'name': 'OPPO Reno 11 Pro', 'brand': 'OPPO', 'price': 11990000, 'compare_price': 13490000,
         'specs': {'ram': '12GB', 'storage': '256GB', 'screen': '6.74 inch'},
         'image': 'https://picsum.photos/seed/reno11pro/400/400'},
        {'name': 'Vivo V30 Pro', 'brand': 'Vivo', 'price': 10990000, 'compare_price': 12490000,
         'specs': {'ram': '12GB', 'storage': '256GB', 'screen': '6.78 inch', 'camera': 'Zeiss'},
         'image': 'https://picsum.photos/seed/vivov30pro/400/400'},
        {'name': 'Samsung Galaxy Z Fold 5', 'brand': 'Samsung', 'price': 43990000, 'compare_price': 49990000,
         'specs': {'ram': '12GB', 'storage': '256GB', 'screen': '7.6 inch foldable', 'chip': 'Snapdragon 8 Gen 2'},
         'image': 'https://picsum.photos/seed/zfold5/400/400'},
        {'name': 'iPhone 14', 'brand': 'Apple', 'price': 17990000, 'compare_price': 19990000,
         'specs': {'ram': '6GB', 'storage': '128GB', 'screen': '6.1 inch', 'chip': 'A15 Bionic'},
         'image': 'https://picsum.photos/seed/iphone14/400/400'},
        {'name': 'Realme GT 5 Pro', 'brand': 'Realme', 'price': 13990000, 'compare_price': 15990000,
         'specs': {'ram': '16GB', 'storage': '512GB', 'screen': '6.78 inch', 'chip': 'Snapdragon 8 Gen 3'},
         'image': 'https://picsum.photos/seed/realmegt5/400/400'},
    ],
    'laptop': [
        {'name': 'MacBook Pro 14 M3 Pro', 'brand': 'Apple', 'price': 49990000, 'compare_price': 52990000,
         'specs': {'ram': '18GB', 'storage': '512GB SSD', 'screen': '14.2 inch', 'chip': 'M3 Pro'},
         'image': 'https://picsum.photos/seed/macbookpro14/400/400'},
        {'name': 'Dell XPS 15', 'brand': 'Dell', 'price': 35990000, 'compare_price': 39990000,
         'specs': {'ram': '16GB', 'storage': '512GB SSD', 'screen': '15.6 inch', 'chip': 'Intel i7-13700H'},
         'image': 'https://picsum.photos/seed/dellxps15/400/400'},
        {'name': 'ASUS ROG Strix G16', 'brand': 'ASUS', 'price': 32990000, 'compare_price': None,
         'specs': {'ram': '16GB', 'storage': '1TB SSD', 'screen': '16 inch', 'gpu': 'RTX 4060'},
         'image': 'https://picsum.photos/seed/rogstrix/400/400'},
        {'name': 'Lenovo ThinkPad X1 Carbon', 'brand': 'Lenovo', 'price': 28990000, 'compare_price': 32990000,
         'specs': {'ram': '16GB', 'storage': '512GB SSD', 'screen': '14 inch', 'chip': 'Intel i7-1365U'},
         'image': 'https://picsum.photos/seed/thinkpadx1/400/400'},
        {'name': 'HP Pavilion 15', 'brand': 'HP', 'price': 15990000, 'compare_price': 17990000,
         'specs': {'ram': '8GB', 'storage': '512GB SSD', 'screen': '15.6 inch', 'chip': 'Intel i5-1335U'},
         'image': 'https://picsum.photos/seed/hppav15/400/400'},
        {'name': 'MacBook Air M2', 'brand': 'Apple', 'price': 27990000, 'compare_price': 29990000,
         'specs': {'ram': '8GB', 'storage': '256GB SSD', 'screen': '13.6 inch', 'chip': 'M2'},
         'image': 'https://picsum.photos/seed/macbookairm2/400/400'},
        {'name': 'Acer Nitro 5', 'brand': 'Acer', 'price': 22990000, 'compare_price': 24990000,
         'specs': {'ram': '16GB', 'storage': '512GB SSD', 'screen': '15.6 inch', 'gpu': 'RTX 4050'},
         'image': 'https://picsum.photos/seed/acernitro5/400/400'},
        {'name': 'MSI Titan GT77', 'brand': 'MSI', 'price': 85990000, 'compare_price': None,
         'specs': {'ram': '64GB', 'storage': '4TB SSD', 'screen': '17.3 inch', 'gpu': 'RTX 4090'},
         'image': 'https://picsum.photos/seed/msititangt77/400/400'},
        {'name': 'Lenovo IdeaPad Slim 5', 'brand': 'Lenovo', 'price': 14990000, 'compare_price': 16990000,
         'specs': {'ram': '16GB', 'storage': '512GB SSD', 'screen': '14 inch', 'chip': 'AMD Ryzen 7'},
         'image': 'https://picsum.photos/seed/ideapadslim5/400/400'},
        {'name': 'ASUS Zenbook 14 OLED', 'brand': 'ASUS', 'price': 24990000, 'compare_price': 27990000,
         'specs': {'ram': '16GB', 'storage': '512GB SSD', 'screen': '14 inch OLED', 'chip': 'Intel i7-1360P'},
         'image': 'https://picsum.photos/seed/zenbook14oled/400/400'},
        {'name': 'Dell Inspiron 15', 'brand': 'Dell', 'price': 13990000, 'compare_price': 15990000,
         'specs': {'ram': '8GB', 'storage': '256GB SSD', 'screen': '15.6 inch', 'chip': 'Intel i5-1235U'},
         'image': 'https://picsum.photos/seed/dellinspirion15/400/400'},
        {'name': 'MacBook Pro 16 M3 Max', 'brand': 'Apple', 'price': 89990000, 'compare_price': None,
         'specs': {'ram': '48GB', 'storage': '1TB SSD', 'screen': '16.2 inch', 'chip': 'M3 Max'},
         'image': 'https://picsum.photos/seed/macbookpro16m3/400/400'},
    ],
    'thoi-trang-nam': [
        {'name': 'Áo Polo Classic', 'brand': 'Routine', 'price': 350000, 'compare_price': 450000,
         'specs': {'material': 'Cotton', 'sizes': 'S, M, L, XL', 'color': 'Trắng, Đen, Navy'},
         'image': 'https://picsum.photos/seed/poloclassic/400/400'},
        {'name': 'Quần Jean Slim Fit', 'brand': "Levi's", 'price': 1290000, 'compare_price': 1590000,
         'specs': {'material': 'Denim', 'sizes': '29-36', 'style': 'Slim Fit'},
         'image': 'https://picsum.photos/seed/jeanslimfit/400/400'},
        {'name': 'Giày Sneaker Air Max', 'brand': 'Nike', 'price': 2490000, 'compare_price': 2990000,
         'specs': {'sizes': '39-44', 'color': 'Trắng', 'sole': 'Air Max'},
         'image': 'https://picsum.photos/seed/nikeairmax/400/400'},
        {'name': 'Áo Khoác Bomber', 'brand': 'Zara', 'price': 1490000, 'compare_price': None,
         'specs': {'material': 'Polyester', 'sizes': 'M, L, XL'},
         'image': 'https://picsum.photos/seed/bombernam/400/400'},
        {'name': 'Quần Short Thể Thao', 'brand': 'Adidas', 'price': 590000, 'compare_price': 750000,
         'specs': {'material': 'Polyester', 'sizes': 'S-XL'},
         'image': 'https://picsum.photos/seed/adidasshortnam/400/400'},
        {'name': 'Áo Thun Oversize', 'brand': 'Uniqlo', 'price': 390000, 'compare_price': None,
         'specs': {'material': '100% Cotton', 'sizes': 'M, L, XL, XXL'},
         'image': 'https://picsum.photos/seed/oversize/400/400'},
        {'name': 'Áo Sơ Mi Linen', 'brand': 'H&M', 'price': 550000, 'compare_price': 690000,
         'specs': {'material': 'Linen 100%', 'sizes': 'S-XL', 'color': 'Trắng, Be, Xanh nhạt'},
         'image': 'https://picsum.photos/seed/linennam/400/400'},
        {'name': 'Quần Kaki Chinos', 'brand': 'Dockers', 'price': 890000, 'compare_price': 1090000,
         'specs': {'material': 'Cotton Kaki', 'sizes': '28-36', 'style': 'Slim Straight'},
         'image': 'https://picsum.photos/seed/chinosnam/400/400'},
        {'name': 'Giày Da Oxford', 'brand': 'Clarks', 'price': 3490000, 'compare_price': 3990000,
         'specs': {'material': 'Da thật', 'sizes': '39-45', 'color': 'Đen, Nâu'},
         'image': 'https://picsum.photos/seed/oxfordnam/400/400'},
        {'name': 'Áo Hoodie Champion', 'brand': 'Champion', 'price': 1290000, 'compare_price': 1590000,
         'specs': {'material': 'Fleece Cotton', 'sizes': 'S-XXL', 'color': 'Nhiều màu'},
         'image': 'https://picsum.photos/seed/hoodiechampion/400/400'},
        {'name': 'Quần Jean Baggy', 'brand': 'Dickies', 'price': 1190000, 'compare_price': None,
         'specs': {'material': 'Denim', 'sizes': '28-36', 'style': 'Baggy'},
         'image': 'https://picsum.photos/seed/jeanbaggyn/400/400'},
    ],
    'thoi-trang-nu': [
        {'name': 'Đầm Maxi Hoa', 'brand': 'Elise', 'price': 1290000, 'compare_price': 1590000,
         'specs': {'material': 'Voan', 'sizes': 'S, M, L', 'style': 'Maxi'},
         'image': 'https://picsum.photos/seed/maxidressnu/400/400'},
        {'name': 'Áo Blouse Lụa', 'brand': 'IVY moda', 'price': 890000, 'compare_price': None,
         'specs': {'material': 'Lụa satin', 'sizes': 'S, M, L'},
         'image': 'https://picsum.photos/seed/blousenu/400/400'},
        {'name': 'Chân Váy Midi', 'brand': 'Zara', 'price': 990000, 'compare_price': 1200000,
         'specs': {'material': 'Polyester', 'sizes': 'XS-L'},
         'image': 'https://picsum.photos/seed/midiskirt/400/400'},
        {'name': 'Giày Cao Gót Block', 'brand': 'Juno', 'price': 690000, 'compare_price': 890000,
         'specs': {'height': '7cm', 'sizes': '35-39', 'color': 'Đen, Nude'},
         'image': 'https://picsum.photos/seed/heelsjuno/400/400'},
        {'name': 'Túi Xách Tote Canvas', 'brand': 'Charles & Keith', 'price': 1490000, 'compare_price': 1790000,
         'specs': {'material': 'Canvas', 'color': 'Đen, Be, Nâu'},
         'image': 'https://picsum.photos/seed/toteck/400/400'},
        {'name': 'Áo Khoác Dạ Tweed', 'brand': 'Elise', 'price': 2490000, 'compare_price': 2990000,
         'specs': {'material': 'Dạ tweed', 'sizes': 'S, M, L'},
         'image': 'https://picsum.photos/seed/dacoatnu/400/400'},
        {'name': 'Quần Jean Ống Rộng', 'brand': "Levi's", 'price': 1490000, 'compare_price': 1890000,
         'specs': {'material': 'Denim', 'sizes': '24-32', 'style': 'Wide Leg'},
         'image': 'https://picsum.photos/seed/widejeansnu/400/400'},
        {'name': 'Áo Crop Top Cotton', 'brand': 'Cotton On', 'price': 290000, 'compare_price': 390000,
         'specs': {'material': '100% Cotton', 'sizes': 'XS-L'},
         'image': 'https://picsum.photos/seed/croptopnu/400/400'},
        {'name': 'Giày Sneaker Platform', 'brand': 'Steve Madden', 'price': 1990000, 'compare_price': 2490000,
         'specs': {'sole': 'Platform 4cm', 'sizes': '35-40', 'color': 'Trắng, Đen'},
         'image': 'https://picsum.photos/seed/platformnu/400/400'},
        {'name': 'Đầm Wrap Lụa', 'brand': 'Diane von Furstenberg', 'price': 3990000, 'compare_price': None,
         'specs': {'material': 'Silk', 'sizes': 'XS-L', 'style': 'Wrap'},
         'image': 'https://picsum.photos/seed/wrapsilknu/400/400'},
        {'name': 'Túi Clutch Da', 'brand': 'Pedro', 'price': 890000, 'compare_price': 1190000,
         'specs': {'material': 'Da PU cao cấp', 'color': 'Đen, Vàng'},
         'image': 'https://picsum.photos/seed/clutchpedro/400/400'},
    ],
    'do-gia-dung': [
        {'name': 'Nồi chiên không dầu 6L Philips', 'brand': 'Philips', 'price': 3490000, 'compare_price': 3990000,
         'specs': {'capacity': '6L', 'power': '2000W', 'features': 'Digital, 8 chế độ'},
         'image': 'https://picsum.photos/seed/airfryerphilips/400/400'},
        {'name': 'Máy hút bụi Robot Xiaomi S10', 'brand': 'Xiaomi', 'price': 7990000, 'compare_price': 8990000,
         'specs': {'suction': '4000Pa', 'battery': '5200mAh', 'features': 'Laser mapping, Mop'},
         'image': 'https://picsum.photos/seed/robotvacxiaomi/400/400'},
        {'name': 'Máy lọc không khí Sharp', 'brand': 'Sharp', 'price': 4990000, 'compare_price': None,
         'specs': {'area': '40m²', 'filter': 'HEPA', 'features': 'Ion Plasmacluster'},
         'image': 'https://picsum.photos/seed/airpurifiersharp/400/400'},
        {'name': 'Bàn ủi hơi nước đứng Tefal', 'brand': 'Tefal', 'price': 1990000, 'compare_price': 2490000,
         'specs': {'power': '1800W', 'tank': '1.5L'},
         'image': 'https://picsum.photos/seed/steameriron/400/400'},
        {'name': 'Máy xay sinh tố Vitamix A3500', 'brand': 'Vitamix', 'price': 12990000, 'compare_price': 14990000,
         'specs': {'power': '2200W', 'capacity': '2L', 'speed': '10 tốc độ + Pulse'},
         'image': 'https://picsum.photos/seed/vitamixa3500/400/400'},
        {'name': 'Nồi cơm điện cao tần Cuckoo', 'brand': 'Cuckoo', 'price': 6490000, 'compare_price': 7490000,
         'specs': {'capacity': '1.8L', 'features': 'IH, áp suất, nấu ngon'},
         'image': 'https://picsum.photos/seed/ricecooker/400/400'},
        {'name': 'Lò vi sóng LG 25L', 'brand': 'LG', 'price': 2990000, 'compare_price': 3490000,
         'specs': {'capacity': '25L', 'power': '1000W', 'features': 'Grill, Convection'},
         'image': 'https://picsum.photos/seed/microwaveLG/400/400'},
        {'name': 'Máy pha cà phê Delonghi', 'brand': 'Delonghi', 'price': 8990000, 'compare_price': 10990000,
         'specs': {'type': 'Espresso', 'pressure': '15 bar', 'features': 'Steam wand'},
         'image': 'https://picsum.photos/seed/delonghicoffee/400/400'},
        {'name': 'Robot hút bụi lau nhà Ecovacs', 'brand': 'Ecovacs', 'price': 12990000, 'compare_price': 14990000,
         'specs': {'suction': '5000Pa', 'features': 'AIVI 3D, Auto Empty'},
         'image': 'https://picsum.photos/seed/ecovacsrobot/400/400'},
        {'name': 'Ấm đun nước Electrolux 1.7L', 'brand': 'Electrolux', 'price': 590000, 'compare_price': 790000,
         'specs': {'capacity': '1.7L', 'power': '2000W', 'material': 'Inox 304'},
         'image': 'https://picsum.photos/seed/electroluxkettle/400/400'},
        {'name': 'Tủ lạnh Samsung Inverter 382L', 'brand': 'Samsung', 'price': 8990000, 'compare_price': 10990000,
         'specs': {'capacity': '382L', 'features': 'Inverter, No Frost', 'color': 'Bạc'},
         'image': 'https://picsum.photos/seed/samsungfridge/400/400'},
    ],
    'sach': [
        {'name': 'Đắc Nhân Tâm', 'brand': 'NXB Tổng hợp', 'price': 86000, 'compare_price': 108000,
         'specs': {'author': 'Dale Carnegie', 'pages': 320, 'format': 'Bìa mềm', 'genre': 'Kỹ năng sống'},
         'image': 'https://picsum.photos/seed/dacnhantam/400/400'},
        {'name': 'Nhà Giả Kim', 'brand': 'NXB Hội Nhà Văn', 'price': 69000, 'compare_price': 79000,
         'specs': {'author': 'Paulo Coelho', 'pages': 228, 'format': 'Bìa mềm', 'genre': 'Tiểu thuyết'},
         'image': 'https://picsum.photos/seed/nhagiakim/400/400'},
        {'name': 'Clean Code', 'brand': 'Prentice Hall', 'price': 590000, 'compare_price': None,
         'specs': {'author': 'Robert C. Martin', 'pages': 464, 'language': 'English', 'genre': 'Lập trình'},
         'image': 'https://picsum.photos/seed/cleancode/400/400'},
        {'name': 'Sapiens: Lược sử loài người', 'brand': 'NXB Tri Thức', 'price': 199000, 'compare_price': 239000,
         'specs': {'author': 'Yuval Noah Harari', 'pages': 520, 'format': 'Bìa cứng', 'genre': 'Lịch sử'},
         'image': 'https://picsum.photos/seed/sapiens/400/400'},
        {'name': 'Atomic Habits', 'brand': 'NXB Lao Động', 'price': 139000, 'compare_price': 179000,
         'specs': {'author': 'James Clear', 'pages': 320, 'language': 'Tiếng Việt', 'genre': 'Kỹ năng'},
         'image': 'https://picsum.photos/seed/atomichabits/400/400'},
        {'name': 'Tư Duy Nhanh Và Chậm', 'brand': 'NXB Thế Giới', 'price': 189000, 'compare_price': 229000,
         'specs': {'author': 'Daniel Kahneman', 'pages': 600, 'format': 'Bìa mềm', 'genre': 'Tâm lý học'},
         'image': 'https://picsum.photos/seed/thinkingfast/400/400'},
        {'name': 'Design Patterns', 'brand': 'Addison-Wesley', 'price': 690000, 'compare_price': None,
         'specs': {'author': 'Gang of Four', 'pages': 395, 'language': 'English', 'genre': 'Lập trình'},
         'image': 'https://picsum.photos/seed/designpatterns/400/400'},
        {'name': 'The Psychology of Money', 'brand': 'NXB Lao Động', 'price': 129000, 'compare_price': 159000,
         'specs': {'author': 'Morgan Housel', 'pages': 256, 'language': 'Tiếng Việt', 'genre': 'Tài chính'},
         'image': 'https://picsum.photos/seed/psychmoney/400/400'},
        {'name': 'Zero to One', 'brand': 'NXB Trẻ', 'price': 119000, 'compare_price': 149000,
         'specs': {'author': 'Peter Thiel', 'pages': 224, 'language': 'Tiếng Việt', 'genre': 'Kinh doanh'},
         'image': 'https://picsum.photos/seed/zerotoone/400/400'},
        {'name': 'Người Giàu Có Nhất Thành Babylon', 'brand': 'NXB Tổng hợp', 'price': 79000, 'compare_price': 99000,
         'specs': {'author': 'George S. Clason', 'pages': 192, 'genre': 'Tài chính cá nhân'},
         'image': 'https://picsum.photos/seed/richestbabylon/400/400'},
        {'name': 'Dune', 'brand': 'Ace Books', 'price': 350000, 'compare_price': None,
         'specs': {'author': 'Frank Herbert', 'pages': 896, 'language': 'English', 'genre': 'Sci-Fi'},
         'image': 'https://picsum.photos/seed/dunebook/400/400'},
        {'name': 'Lập trình Python cho người mới', 'brand': 'NXB Thống kê', 'price': 249000, 'compare_price': 299000,
         'specs': {'author': 'Nguyễn Minh Đức', 'pages': 450, 'language': 'Tiếng Việt', 'genre': 'Lập trình'},
         'image': 'https://picsum.photos/seed/pythonviet/400/400'},
    ],
    'the-thao': [
        {'name': 'Vợt cầu lông Yonex Astrox 88D', 'brand': 'Yonex', 'price': 3490000, 'compare_price': 3990000,
         'specs': {'weight': '83g', 'balance': 'Head Heavy', 'material': 'Carbon', 'level': 'Advanced'},
         'image': 'https://picsum.photos/seed/yonexastrox/400/400'},
        {'name': 'Giày chạy bộ Ultraboost 22', 'brand': 'Adidas', 'price': 4290000, 'compare_price': 4990000,
         'specs': {'sizes': '39-45', 'sole': 'Boost', 'weight': '310g', 'terrain': 'Road'},
         'image': 'https://picsum.photos/seed/ultraboost22/400/400'},
        {'name': 'Bóng đá Adidas UCL Pro', 'brand': 'Adidas', 'price': 1290000, 'compare_price': None,
         'specs': {'size': '5', 'material': 'PU', 'certification': 'FIFA Pro'},
         'image': 'https://picsum.photos/seed/soccerball/400/400'},
        {'name': 'Thảm Yoga TPE 8mm', 'brand': 'Manduka', 'price': 1290000, 'compare_price': 1590000,
         'specs': {'thickness': '8mm', 'material': 'TPE', 'size': '183x61cm'},
         'image': 'https://picsum.photos/seed/yogamat8mm/400/400'},
        {'name': 'Bộ tạ tay 20kg Cast Iron', 'brand': 'Reebok', 'price': 1990000, 'compare_price': 2290000,
         'specs': {'weight': '20kg set', 'material': 'Cast Iron', 'includes': '2 bars, 8 plates'},
         'image': 'https://picsum.photos/seed/dumbbellset/400/400'},
        {'name': 'Áo thể thao DRI-FIT', 'brand': 'Nike', 'price': 890000, 'compare_price': 1090000,
         'specs': {'material': 'Polyester DRI-FIT', 'sizes': 'S-XXL', 'feature': 'Quick dry'},
         'image': 'https://picsum.photos/seed/nikdrifit/400/400'},
        {'name': 'Xe đạp địa hình Trek Marlin 5', 'brand': 'Trek', 'price': 14990000, 'compare_price': 16990000,
         'specs': {'frame': 'Aluminum', 'gears': '21 tốc độ', 'wheel': '29 inch'},
         'image': 'https://picsum.photos/seed/trekmtb/400/400'},
        {'name': 'Giày chạy bộ Nike Air Zoom Pegasus', 'brand': 'Nike', 'price': 3590000, 'compare_price': 3990000,
         'specs': {'sizes': '38-46', 'sole': 'Zoom Air', 'weight': '280g'},
         'image': 'https://picsum.photos/seed/nikepegasus/400/400'},
        {'name': 'Găng tay boxing Everlast', 'brand': 'Everlast', 'price': 890000, 'compare_price': 1090000,
         'specs': {'weight': '12oz', 'material': 'PU da', 'sizes': 'S/M, L/XL'},
         'image': 'https://picsum.photos/seed/boxinggloves/400/400'},
        {'name': 'Bóng rổ Spalding NBA Official', 'brand': 'Spalding', 'price': 1590000, 'compare_price': None,
         'specs': {'size': '7', 'material': 'Da tổng hợp', 'certification': 'NBA Official'},
         'image': 'https://picsum.photos/seed/basketballnba/400/400'},
        {'name': 'Dây nhảy thể thao Crossrope', 'brand': 'Crossrope', 'price': 490000, 'compare_price': 590000,
         'specs': {'material': 'Steel cable', 'handle': 'Aluminum', 'length': 'Adjustable'},
         'image': 'https://picsum.photos/seed/jumprope/400/400'},
    ],
    'my-pham': [
        {'name': 'Kem chống nắng UV Expert SPF50+', 'brand': "L'Oreal", 'price': 390000, 'compare_price': 450000,
         'specs': {'spf': '50+ PA++++', 'volume': '50ml', 'type': 'Lightweight, non-greasy'},
         'image': 'https://picsum.photos/seed/sunscreenloreal/400/400'},
        {'name': 'Serum Vitamin C 20% Klairs', 'brand': 'Klairs', 'price': 490000, 'compare_price': None,
         'specs': {'volume': '35ml', 'ingredients': 'Vitamin C, Niacinamide', 'skin_type': 'All types'},
         'image': 'https://picsum.photos/seed/vitcserumklairs/400/400'},
        {'name': 'Sữa rửa mặt Amino Acid CeraVe', 'brand': 'CeraVe', 'price': 290000, 'compare_price': 350000,
         'specs': {'volume': '236ml', 'skin_type': 'Normal to Oily', 'ph': '5.5'},
         'image': 'https://picsum.photos/seed/facewashcerave/400/400'},
        {'name': 'Nước tẩy trang Micellar Bioderma', 'brand': 'Bioderma', 'price': 350000, 'compare_price': 420000,
         'specs': {'volume': '500ml', 'type': 'Sensibio H2O', 'skin_type': 'Sensitive'},
         'image': 'https://picsum.photos/seed/micellarbioderm/400/400'},
        {'name': 'Mặt nạ ngủ Water Sleeping Mask Laneige', 'brand': 'Laneige', 'price': 590000, 'compare_price': 690000,
         'specs': {'volume': '70ml', 'type': 'Water Sleeping Mask', 'use': 'Night'},
         'image': 'https://picsum.photos/seed/laneigesleepmask/400/400'},
        {'name': 'Son môi Rouge Dior 999', 'brand': 'Dior', 'price': 990000, 'compare_price': None,
         'specs': {'type': 'Matte', 'shade': '999 Red', 'weight': '3.5g', 'finish': 'Velvet'},
         'image': 'https://picsum.photos/seed/diorrougelip/400/400'},
        {'name': 'Nước hoa Chanel Chance EDP', 'brand': 'Chanel', 'price': 3290000, 'compare_price': 3690000,
         'specs': {'volume': '50ml', 'type': 'Eau de Parfum', 'notes': 'Citrus, Jasmine, Musk'},
         'image': 'https://picsum.photos/seed/chanelchanceedp/400/400'},
        {'name': 'Kem dưỡng ẩm Neutrogena Hydro Boost', 'brand': 'Neutrogena', 'price': 450000, 'compare_price': 550000,
         'specs': {'volume': '50ml', 'ingredient': 'Hyaluronic Acid', 'skin_type': 'Dry, Dehydrated'},
         'image': 'https://picsum.photos/seed/neutrogenahydro/400/400'},
        {'name': 'Tẩy tế bào chết Paula\'s Choice BHA', 'brand': "Paula's Choice", 'price': 890000, 'compare_price': None,
         'specs': {'volume': '118ml', 'ingredient': 'BHA 2%', 'type': 'Leave-on exfoliant'},
         'image': 'https://picsum.photos/seed/paulabha/400/400'},
        {'name': 'Retinol Serum The Ordinary 1%', 'brand': 'The Ordinary', 'price': 390000, 'compare_price': 450000,
         'specs': {'volume': '30ml', 'ingredient': 'Retinol 1%', 'use': 'Night only'},
         'image': 'https://picsum.photos/seed/theordinaryretinol/400/400'},
        {'name': 'Phấn nước Cushion Hera Black', 'brand': 'Hera', 'price': 890000, 'compare_price': 990000,
         'specs': {'shade': 'N21, N23, N25', 'finish': 'Dewy', 'spf': 'SPF34 PA++'},
         'image': 'https://picsum.photos/seed/heracushion/400/400'},
        {'name': 'Mascara Maybelline Sky High', 'brand': 'Maybelline', 'price': 189000, 'compare_price': 229000,
         'specs': {'volume': '7.2ml', 'effect': 'Lengthening & Volumizing', 'waterproof': True},
         'image': 'https://picsum.photos/seed/maybellinemascara/400/400'},
    ],
    'dong-ho': [
        {'name': 'Apple Watch Series 9 GPS 45mm', 'brand': 'Apple', 'price': 10990000, 'compare_price': 11990000,
         'specs': {'screen': '45mm OLED', 'battery': '18h', 'features': 'ECG, SpO2, Crash Detection', 'os': 'watchOS'},
         'image': 'https://picsum.photos/seed/applewatch9/400/400'},
        {'name': 'Samsung Galaxy Watch 6 Classic 47mm', 'brand': 'Samsung', 'price': 8990000, 'compare_price': 9990000,
         'specs': {'screen': '47mm AMOLED', 'battery': '40h', 'features': 'BioActive, Advanced Sleep', 'os': 'Wear OS'},
         'image': 'https://picsum.photos/seed/galaxywatch6/400/400'},
        {'name': 'Garmin Fenix 7 Solar', 'brand': 'Garmin', 'price': 15990000, 'compare_price': 18990000,
         'specs': {'screen': '1.3 inch', 'battery': '37 ngày', 'features': 'Solar, GPS, Multi-sport', 'grade': 'Military'},
         'image': 'https://picsum.photos/seed/garminfenix7/400/400'},
        {'name': 'Xiaomi Mi Watch S3 AMOLED', 'brand': 'Xiaomi', 'price': 2990000, 'compare_price': 3490000,
         'specs': {'screen': '1.43 inch AMOLED', 'battery': '15 ngày', 'features': 'SpO2, 150+ thể thao'},
         'image': 'https://picsum.photos/seed/xiaomiwatchs3/400/400'},
        {'name': 'Casio G-Shock GA-2100', 'brand': 'Casio', 'price': 3490000, 'compare_price': None,
         'specs': {'features': 'Chống va đập, Chống nước 200m', 'battery': 'Pin 2 năm', 'material': 'Carbon core'},
         'image': 'https://picsum.photos/seed/casiogshock/400/400'},
        {'name': 'Seiko 5 Sports Automatic', 'brand': 'Seiko', 'price': 5990000, 'compare_price': 6990000,
         'specs': {'movement': 'Automatic', 'water_resist': '100m', 'case': 'Stainless Steel'},
         'image': 'https://picsum.photos/seed/seiko5sports/400/400'},
        {'name': 'Fossil Gen 6 Hybrid Smartwatch', 'brand': 'Fossil', 'price': 4990000, 'compare_price': 5990000,
         'specs': {'screen': '1.28 inch', 'battery': '14 ngày', 'features': 'Alexa built-in, Heart Rate'},
         'image': 'https://picsum.photos/seed/fossilgen6/400/400'},
        {'name': 'Fitbit Versa 4', 'brand': 'Fitbit', 'price': 4490000, 'compare_price': 4990000,
         'specs': {'screen': 'AMOLED', 'battery': '6 ngày', 'features': 'GPS, Alexa, SpO2, Sleep Score'},
         'image': 'https://picsum.photos/seed/fitbitversa4/400/400'},
        {'name': 'Citizen Eco-Drive Promaster', 'brand': 'Citizen', 'price': 8990000, 'compare_price': 10990000,
         'specs': {'movement': 'Eco-Drive (Solar)', 'water_resist': '200m', 'features': 'Dive Computer'},
         'image': 'https://picsum.photos/seed/citizeneco/400/400'},
        {'name': 'Huawei Watch GT 4 Pro', 'brand': 'Huawei', 'price': 6990000, 'compare_price': 7990000,
         'specs': {'screen': '1.5 inch AMOLED', 'battery': '14 ngày', 'features': 'ECG, SpO2, Temperature'},
         'image': 'https://picsum.photos/seed/huaweiwatchgt4/400/400'},
        {'name': 'Amazfit GTR 4', 'brand': 'Amazfit', 'price': 3990000, 'compare_price': 4490000,
         'specs': {'screen': '1.43 inch AMOLED', 'battery': '14 ngày', 'gps': 'Dual Band GPS', 'features': '150+ chế độ thể thao'},
         'image': 'https://picsum.photos/seed/amazfitgtr4/400/400'},
    ],
    'am-thanh': [
        {'name': 'Apple AirPods Pro 2 (USB-C)', 'brand': 'Apple', 'price': 6490000, 'compare_price': 6990000,
         'specs': {'anc': 'Active Noise Cancellation', 'battery': '30h (với case)', 'audio': 'Adaptive Audio', 'chip': 'H2'},
         'image': 'https://picsum.photos/seed/airpodspro2/400/400'},
        {'name': 'Sony WH-1000XM5', 'brand': 'Sony', 'price': 7990000, 'compare_price': 8990000,
         'specs': {'type': 'Over-ear', 'anc': 'Industry-leading ANC', 'battery': '30h', 'codecs': 'LDAC, AAC, SBC'},
         'image': 'https://picsum.photos/seed/sonywh1000xm5/400/400'},
        {'name': 'Samsung Galaxy Buds 2 Pro', 'brand': 'Samsung', 'price': 4490000, 'compare_price': 4990000,
         'specs': {'type': 'In-ear TWS', 'anc': 'Active Noise Cancellation', 'battery': '18h', 'audio': '24-bit Hi-Fi'},
         'image': 'https://picsum.photos/seed/galaxybuds2pro/400/400'},
        {'name': 'Bose QuietComfort 45', 'brand': 'Bose', 'price': 8490000, 'compare_price': 9490000,
         'specs': {'type': 'Over-ear', 'anc': 'Quiet Mode & Aware Mode', 'battery': '24h', 'foldable': True},
         'image': 'https://picsum.photos/seed/bosequietcomfort45/400/400'},
        {'name': 'JBL Charge 5 Portable Speaker', 'brand': 'JBL', 'price': 2990000, 'compare_price': 3490000,
         'specs': {'battery': '20h', 'waterproof': 'IP67', 'power': '40W', 'features': 'PowerBank, Party Boost'},
         'image': 'https://picsum.photos/seed/jblcharge5/400/400'},
        {'name': 'Marshall Emberton II', 'brand': 'Marshall', 'price': 3490000, 'compare_price': None,
         'specs': {'battery': '30h', 'waterproof': 'IPX7', 'power': '20W', 'features': 'True Stereo Sound'},
         'image': 'https://picsum.photos/seed/marshallemb2/400/400'},
        {'name': 'Sony WF-1000XM4', 'brand': 'Sony', 'price': 4990000, 'compare_price': 5990000,
         'specs': {'type': 'In-ear TWS', 'anc': 'Integrated Processor V1', 'battery': '24h', 'codecs': 'LDAC'},
         'image': 'https://picsum.photos/seed/sonywf1000xm4/400/400'},
        {'name': 'Anker Soundcore Liberty 4 NC', 'brand': 'Anker', 'price': 1290000, 'compare_price': 1590000,
         'specs': {'type': 'In-ear TWS', 'anc': '98.5% Noise Reduction', 'battery': '50h', 'audio': 'LDAC Hi-Res'},
         'image': 'https://picsum.photos/seed/ankerliberty4nc/400/400'},
        {'name': 'JBL Flip 6 Portable Speaker', 'brand': 'JBL', 'price': 1990000, 'compare_price': 2290000,
         'specs': {'battery': '12h', 'waterproof': 'IP67', 'power': '20W', 'features': 'PartyBoost'},
         'image': 'https://picsum.photos/seed/jblflip6/400/400'},
        {'name': 'Jabra Evolve2 85 Wireless', 'brand': 'Jabra', 'price': 9990000, 'compare_price': None,
         'specs': {'type': 'Over-ear Business', 'anc': 'Advanced ANC', 'battery': '37h', 'features': 'UC Certified, 8 mic'},
         'image': 'https://picsum.photos/seed/jabraevolve2/400/400'},
        {'name': 'Harman Kardon Onyx Studio 8', 'brand': 'Harman Kardon', 'price': 5990000, 'compare_price': 6990000,
         'specs': {'battery': '8h', 'power': '50W', 'features': 'Stereo Sound, Party Mode'},
         'image': 'https://picsum.photos/seed/harmanonyx8/400/400'},
    ],
}


class Command(BaseCommand):
    help = 'Seed categories and products (idempotent)'

    def add_arguments(self, parser):
        parser.add_argument('--noinput', action='store_true')

    def handle(self, *args, **options):
        self.stdout.write('Seeding categories and products...')

        cat_map = {}
        for cat_data in CATEGORIES:
            cat, _ = Category.objects.get_or_create(
                slug=cat_data['slug'],
                defaults={
                    'name': cat_data['name'],
                    'description': cat_data['description'],
                },
            )
            cat_map[cat_data['slug']] = cat

        count = 0
        new_count = 0
        for cat_slug, products in PRODUCTS.items():
            category = cat_map[cat_slug]
            for i, p in enumerate(products):
                slug = slugify(p['name'])
                sku = f'{cat_slug[:3].upper()}-{str(count + 1).zfill(4)}'

                _, created = Product.objects.get_or_create(
                    sku=sku,
                    defaults={
                        'name': p['name'],
                        'slug': slug if not Product.objects.filter(slug=slug).exists() else f'{slug}-{count}',
                        'description': f'{p["name"]} - Sản phẩm chính hãng, chất lượng cao. {category.description}',
                        'category': category,
                        'brand': p.get('brand', ''),
                        'price': p['price'],
                        'compare_price': p.get('compare_price'),
                        'stock_quantity': random.randint(10, 200),
                        'sold_count': random.randint(0, 500),
                        'specifications': p.get('specs', {}),
                        'image_url': p.get('image', ''),
                        'images': [
                            f'https://picsum.photos/seed/{slug}-{j}/400/400'
                            for j in range(1, 4)
                        ],
                        'rating_avg': round(random.uniform(3.5, 5.0), 2),
                        'rating_count': random.randint(5, 300),
                    },
                )
                if created:
                    new_count += 1
                count += 1

        total = Product.objects.count()
        self.stdout.write(self.style.SUCCESS(
            f'Added {new_count} new products. Total products: {total}'
        ))
